# Generated by Django 4.2.7 on 2023-12-11 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
    ]
